### ISSUE TITLE
Still having issues getting the bot to work

### ISSUE THREAD

**Issue by superJK92iscool** [Rapptz/RoboDanny#127]
#126 

I fixed the issues that pip caused now I get this
`Could not load cogs.meta.
Traceback (most recent call last):
  File "launcher.py", line 112, in init
    importlib.import_module(ext)
  File "C:\Users\super\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\super\Desktop\RoboDanny\Rdanny\RoboDanny\cogs\meta.py", line 2, in <module>
    from .utils import checks, formats, time
  File "C:\Users\super\Desktop\RoboDanny\Rdanny\RoboDanny\cogs\utils\time.py", line 3, in <module>
    from dateutil.relativedelta import relativedelta
ValueError: source code string cannot contain null bytes` which has nothing to do with pip (I think)

**Comment by superJK92iscool** [comment]
Please help me with this anyone

**Comment by superJK92iscool** [comment]
Since nobody is going to help me with this I may as well close the issue and leave the discord server because there isn't a point on trying to have someone help me with it

**Comment by superJK92iscool** [comment]
closed because nobody would help me with it even though I asked
