### ISSUE TITLE
Please help me with this issue

### ISSUE THREAD

**Issue by superJK92iscool** [Rapptz/RoboDanny#128]
I keep getting 

`Could not load cogs.meta.
Traceback (most recent call last):
  File "launcher.py", line 112, in init
    importlib.import_module(ext)
  File "C:\Users\super\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\super\Desktop\RoboDanny\Rdanny\RoboDanny\cogs\meta.py", line 2, in <module>
    from .utils import checks, formats, time
  File "C:\Users\super\Desktop\RoboDanny\Rdanny\RoboDanny\cogs\utils\time.py", line 3, in <module>
    from dateutil.relativedelta import relativedelta
ValueError: source code string cannot contain null bytes`

If someone help me I will join the discord again.

**Comment by superJK92iscool** [comment]
and if I don't get help then I will be sad

**Comment by superJK92iscool** [comment]
please help me with this issue

**Comment by superJK92iscool** [comment]
I need help with this issue

**Comment by Rapptz** [comment]
The file you downloaded was somehow not in UTF-8 encoding. I don't know how. It's outside of the scope of this issue tracker. Convert the encoding to valid UTF-8 and remove the null bytes. A simple google search would have led you [here](https://stackoverflow.com/questions/31233777/python-source-code-string-cannot-contain-null-bytes).

**Comment by superJK92iscool** [comment]
I tried but got this 
![F5949B52-31C8-4FC2-8C80-AE4162C05EAB](https://user-images.githubusercontent.com/50285310/129254241-56c603be-9d98-4593-93e3-c8a3ad1d17c0.jpeg) and it is in UTF-8

**Comment by Rapptz** [comment]
UTF-8 doesn't have null bytes by definition.
