### ISSUE TITLE
failed to apply migrations due to error

### ISSUE THREAD

**Issue by OrdinaryEnder** [Rapptz/RoboDanny#160]
Logs:
```py
Traceback (most recent call last):
  File "/sec/root/projecy/RoboDanny/launcher.py", line 298, in upgrade
    applied = asyncio.run(run_upgrade(migrations))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/sec/root/projecy/RoboDanny/launcher.py", line 284, in run_upgrade
    return await migrations.upgrade(connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sec/root/projecy/RoboDanny/launcher.py", line 142, in upgrade
    await connection.execute(sql)
  File "/usr/local/lib/python3.11/dist-packages/asyncpg/connection.py", line 317, in execute
    return await self._protocol.query(query, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncpg/protocol/protocol.pyx", line 338, in query
  File "asyncpg/protocol/protocol.pyx", line 850, in asyncpg.protocol.protocol.BaseProtocol._dispatch_result
  File "asyncpg/protocol/protocol.pyx", line 777, in asyncpg.protocol.protocol.BaseProtocol._on_result__simple_query
AttributeError: 'NoneType' object has no attribute 'decode'
```

System:
```
OS: Kali GNU/Linux Rolling x86_64               
PostgreSQL Version: 15
Python Version: 3.11.2
```

**Comment by Rapptz** [comment]
Not enough info. What did you do?

**Comment by OrdinaryEnder** [comment]
> Not enough info. What did you do?

I was doing `python3 launcher.py db upgrade` and suddenly I got this issue

**Comment by Rapptz** [comment]
Did you do `launcher.py db init` before doing that?

**Comment by OrdinaryEnder** [comment]
> Did you do `launcher.py db init` before doing that?

I did

**Comment by Rapptz** [comment]
Then you most likely have an empty migration file somewhere being applied.

**Comment by OrdinaryEnder** [comment]
> Then you most likely have an empty migration file somewhere being applied.

How do I handle this?

**Comment by Rapptz** [comment]
Delete the empty migration file, change the `migrations.json` file to point to `0` for current migration and run `launcher.py db upgrade` again.

**Comment by OrdinaryEnder** [comment]
> Delete the empty migration file, change the `migrations.json` file to point to `0` for current migration and run `launcher.py db upgrade` again.

Idk where it located I'm too dumb for this one
