### ISSUE TITLE
AttributeError: module 'config' has no attribute 'stat_webhook'

### ISSUE THREAD

**Issue by tomlin7** [Rapptz/RoboDanny#82]
**AttributeError: module 'config' has no attribute 'stat_webhook'**

the following is a part of [stats.py](https://github.com/Rapptz/RoboDanny/cogs/stats.py)
```py
    @discord.utils.cached_property
    def webhook(self):
        wh_id, wh_token = self.bot.config.stat_webhook
        hook = discord.Webhook.partial(id=wh_id, token=wh_token, adapter=discord.AsyncWebhookAdapter(self.bot.session))
        return hook
``` 
the error is thrown from this function - line 3 (RoboDanny-rewrite\cogs\stats.py, line 142)

following is the error:
```py
Unhandled exception in internal background task 'gateway_worker'.
Traceback (most recent call last):
  File "C:\Users\billy\AppData\Roaming\Python\Python38\site-packages\discord\ext\tasks\__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "C:\Users\billy\OneDrive\Documents\GitHub\RoboDanny-rewrite\RoboDanny-rewrite\cogs\stats.py", line 103, in gateway_worker
    await self.notify_gateway_status(record)
  File "C:\Users\billy\OneDrive\Documents\GitHub\RoboDanny-rewrite\RoboDanny-rewrite\cogs\stats.py", line 640, in notify_gateway_status
    await self.webhook.send(msg, username='Gateway', avatar_url='https://i.imgur.com/4PnCKB3.png')
  File "C:\Users\billy\AppData\Roaming\Python\Python38\site-packages\discord\utils.py", line 55, in __get__
    value = self.function(instance)
  File "C:\Users\billy\OneDrive\Documents\GitHub\RoboDanny-rewrite\RoboDanny-rewrite\cogs\stats.py", line 142, in webhook
    wh_id, wh_token = self.bot.config.stat_webhook
AttributeError: module 'config' has no attribute 'stat_webhook'
```

**Comment by ghost** [comment]
You are trying to access the `stat_webhook` attribute from the config.py file but you haven't defined it yet.
You should create your own webhook and assign its credentials to a variable called `stat_webhook` in the config.py file.

EDIT:

More info on how to create a webhook [here](https://support.discord.com/hc/en-us/articles/228383668-Come-usare-i-Webhooks)

Then on config.py you should add something like:
```py
stat_webhook = (your_webhook_ID, "your_webhook_token")
```

**Comment by Rapptz** [comment]
This is part of the config. I haven't updated the README probably.
