### ISSUE TITLE
getting when doing `python launcher.py db init`

### ISSUE THREAD

**Issue by AdityaBhushan1** [Rapptz/RoboDanny#95]
```
could not create PostgreSQL connection pool.
Traceback (most recent call last):
  File "launcher.py", line 100, in init
    run(Table.create_pool(config.postgresql))
  File "D:\program files\python3.8.6\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\adity\Documents\GitHub\RoboDanny\cogs\utils\db.py", line 511, in create_pool
    cls._pool = pool = await asyncpg.create_pool(uri, init=init, **kwargs)
  File "C:\Users\adity\AppData\Roaming\Python\Python38\site-packages\asyncpg\pool.py", line 398, in _async__init__
    await self._initialize()
  File "C:\Users\adity\AppData\Roaming\Python\Python38\site-packages\asyncpg\pool.py", line 426, in _initialize
    await first_ch.connect()
  File "C:\Users\adity\AppData\Roaming\Python\Python38\site-packages\asyncpg\pool.py", line 125, in connect
    self._con = await self._pool._get_new_connection()
  File "C:\Users\adity\AppData\Roaming\Python\Python38\site-packages\asyncpg\pool.py", line 468, in _get_new_connection
    con = await connection.connect(
  File "C:\Users\adity\AppData\Roaming\Python\Python38\site-packages\asyncpg\connection.py", line 1718, in connect
    return await connect_utils._connect(
  File "C:\Users\adity\AppData\Roaming\Python\Python38\site-packages\asyncpg\connect_utils.py", line 674, in _connect
    raise last_error
  File "C:\Users\adity\AppData\Roaming\Python\Python38\site-packages\asyncpg\connect_utils.py", line 663, in _connect
    con = await _connect_addr(
  File "C:\Users\adity\AppData\Roaming\Python\Python38\site-packages\asyncpg\connect_utils.py", line 632, in _connect_addr
    tr, pr = await asyncio.wait_for(
  File "D:\program files\python3.8.6\lib\asyncio\tasks.py", line 491, in wait_for
    return fut.result()
  File "D:\program files\python3.8.6\lib\asyncio\base_events.py", line 986, in create_connection
    infos = await self._ensure_resolved(
  File "D:\program files\python3.8.6\lib\asyncio\base_events.py", line 1365, in _ensure_resolved
    return await loop.getaddrinfo(host, port, family=family, type=type,
  File "D:\program files\python3.8.6\lib\asyncio\base_events.py", line 825, in getaddrinfo
    return await self.run_in_executor(
  File "D:\program files\python3.8.6\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\program files\python3.8.6\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

```

**Comment by OoLunar** [comment]
Not specific to your problem, but take a look at this: https://stackoverflow.com/a/18401176

Always be sure to Google your errors before posting a new issue. By the looks of it, R. Danny just couldn't connect to your database host.

**Comment by AdityaBhushan1** [comment]
that error got solved but i got this error
```py
Could not create PostgreSQL connection pool.
Traceback (most recent call last):
  File "launcher.py", line 100, in init
    run(Table.create_pool(config.postgresql))
  File "D:\program files\python3.8.6\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\adity\Documents\GitHub\RoboDanny\cogs\utils\db.py", line 511, in create_pool    
    cls._pool = pool = await asyncpg.create_pool(uri, init=init, **kwargs)
  File "C:\Users\adity\AppData\Roaming\Python\Python38\site-packages\asyncpg\pool.py", line 398, in _async__init__
    await self._initialize()
  File "C:\Users\adity\AppData\Roaming\Python\Python38\site-packages\asyncpg\pool.py", line 426, in _initialize
    await first_ch.connect()
  File "C:\Users\adity\AppData\Roaming\Python\Python38\site-packages\asyncpg\pool.py", line 125, in connect
    self._con = await self._pool._get_new_connection()
  File "C:\Users\adity\AppData\Roaming\Python\Python38\site-packages\asyncpg\pool.py", line 468, in _get_new_connection
    con = await connection.connect(
  File "C:\Users\adity\AppData\Roaming\Python\Python38\site-packages\asyncpg\connection.py", line 1718, in connect
    return await connect_utils._connect(
  File "C:\Users\adity\AppData\Roaming\Python\Python38\site-packages\asyncpg\connect_utils.py", line 674, in _connect
    raise last_error
  File "C:\Users\adity\AppData\Roaming\Python\Python38\site-packages\asyncpg\connect_utils.py", line 663, in _connect
    con = await _connect_addr(
  File "C:\Users\adity\AppData\Roaming\Python\Python38\site-packages\asyncpg\connect_utils.py", line 642, in _connect_addr
    await asyncio.wait_for(connected, timeout=timeout)
  File "D:\program files\python3.8.6\lib\asyncio\tasks.py", line 498, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
```
i searched it on goolge but did not got solution

**Comment by OoLunar** [comment]
Your connection timed out, as the last line states. Usually this happens when you have bad internet...

**Comment by AdityaBhushan1** [comment]
> Your connection timed out, as the last line states. Usually this happens when you have bad internet...

how can i solve that but i have good internet connection of 30mbps

**Comment by OoLunar** [comment]
Just make sure that the connection between your database and R. Danny is fast and secure. One sure-fire way to fix this is by hosting the database with whatever your hosting R. Danny on. Just set the host to `localhost` and install PostgreSQL on whatever R. Danny is on. Regardless, this isn't really a R. Danny issue but rather a database/internet issue.

**Comment by AdityaBhushan1** [comment]
> Just make sure that the connection between your database and R. Danny is fast and secure. One sure-fire way to fix this is by hosting the database with whatever your hosting R. Danny on. Just set the host to `localhost` and install PostgreSQL on whatever R. Danny is on. Regardless, this isn't really a R. Danny issue but rather a database/internet issue.

its already set to local host and postgreSQL is also installed

**Comment by OoLunar** [comment]
Is PostgreSQL running?

**Comment by AdityaBhushan1** [comment]
> Is PostgreSQL running?

yes its running

**Comment by OoLunar** [comment]
Check the PostgreSQL logs. Again, this isn't a R. Danny issue but rather a database issue. Come join https://discord.gg/code and head to the #databases channel. We can help you there

**Comment by AdityaBhushan1** [comment]
> Check the PostgreSQL logs. Again, this isn't a R. Danny issue but rather a database issue. Come join https://discord.gg/code and head to the #databases channel. We can help you there

ok

**Comment by AdityaBhushan1** [comment]
> Check the PostgreSQL logs. Again, this isn't a R. Danny issue but rather a database issue. Come join https://discord.gg/code and head to the #databases channel. We can help you there

sir i came there see database channel

**Comment by OoLunar** [comment]
Awesome. I got it from here, please close the issue
